format_version: v1.0
type: UniqueComponent
attributes: {id: can2}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CALCULATED_DATA_BITRATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '2000'}
  - type: String
    attributes: {id: CALCULATED_DATA_ERRORRATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '0.000'}
  - type: Integer
    attributes: {id: CALCULATED_NOMINAL_BITRATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '500'}
  - type: String
    attributes: {id: CALCULATED_NOMINAL_ERRORRATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '0.000'}
  - type: Integer
    attributes: {id: CAN_CORE_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '100000000'}
  - type: Comment
    attributes: {id: CAN_CORE_CLOCK_INVALID_DATA_BITRAT_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: Warning!!! CAN2 Clock Frequency is too high for required
            Data Bit Timing}
  - type: Comment
    attributes: {id: CAN_DATA_ERRORRATE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: CAN_MULTI_VECTOR_INTERRUPT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: 'true'}
  - type: Comment
    attributes: {id: CAN_NOMINAL_ERRORRATE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Comment
    attributes: {id: CAN_TIME_QUANTA_INVALID_DATA_BITRATE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: Warning!!! Number of Time Quanta is too high for required
            Data Bit Timing}
  - type: Integer
    attributes: {id: DATA_BITRATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2000'}
  - type: String
    attributes: {id: DATA_TIME_QUANTA_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '20.000'}
  - type: Integer
    attributes: {id: DBT_BRP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: DBT_SJW}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '7'}
  - type: Integer
    attributes: {id: DBT_TOTAL_TIME_QUANTA}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '25'}
  - type: Integer
    attributes: {id: DBT_TSEG1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '17'}
  - type: Integer
    attributes: {id: DBT_TSEG2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '7'}
  - type: String
    attributes: {id: FIFO_OFFSET}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '0x3'}
  - type: String
    attributes: {id: FILTER_OBJ_MASK_OFFSET}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '0x2'}
  - type: String
    attributes: {id: FILTER_OFFSET}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '0x1'}
  - type: Integer
    attributes: {id: NBT_BRP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '9'}
  - type: Integer
    attributes: {id: NBT_SJW}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '5'}
  - type: Integer
    attributes: {id: NBT_TOTAL_TIME_QUANTA}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '20'}
  - type: Integer
    attributes: {id: NBT_TSEG1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '14'}
  - type: Integer
    attributes: {id: NBT_TSEG2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '5'}
  - type: String
    attributes: {id: NOMINAL_TIME_QUANTA_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can2, value: '100.000'}
- type: ElementPosition
  attributes: {x: '340', y: '20', id: can2}
