files:
- generatedChecksum: 39FF52903D784BEF79D3640DC1072AFA
  logicalPath: config\pic32mz_w1_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 39FF52903D784BEF79D3640DC1072AFA
- generatedChecksum: 07D8600DBCBE87B8600F5805250A9336
  logicalPath: config\pic32mz_w1_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 07D8600DBCBE87B8600F5805250A9336
- generatedChecksum: D4A2BEA3621A0F5CDC8B22F45AA4BB50
  logicalPath: config\pic32mz_w1_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D4A2BEA3621A0F5CDC8B22F45AA4BB50
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 1F1655EB36B5EB6364972E96A80CDE6C
  logicalPath: config\pic32mz_w1_curiosity\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1F1655EB36B5EB6364972E96A80CDE6C
- generatedChecksum: 05B0DF66636B3C82AF1F827148F68CA6
  logicalPath: config\pic32mz_w1_curiosity\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 05B0DF66636B3C82AF1F827148F68CA6
- generatedChecksum: A2BEAF440AC19A571FE122C9629DD9F0
  logicalPath: config\pic32mz_w1_curiosity\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A2BEAF440AC19A571FE122C9629DD9F0
- generatedChecksum: A0DD613319D0A280DB1DD0B85856B496
  logicalPath: config\pic32mz_w1_curiosity\peripheral\i2c\master
  name: plib_i2c1_master.c
  physicalPath: peripheral\i2c\master
  security: NON_SECURE
  type: SOURCE
  userChecksum: A0DD613319D0A280DB1DD0B85856B496
- generatedChecksum: 9A49A2339A0774ACCBC2178A9EE76586
  logicalPath: config\pic32mz_w1_curiosity
  name: system_pmu_mldo_trim.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9A49A2339A0774ACCBC2178A9EE76586
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mz_w1_curiosity\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: F2BECC75CCD1CCA53E9362CACF0B7872
  logicalPath: config\pic32mz_w1_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F2BECC75CCD1CCA53E9362CACF0B7872
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mz_w1_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mz_w1_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 9238A3759A2C6748FE493370DE35B5E0
  logicalPath: config\pic32mz_w1_curiosity\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 9238A3759A2C6748FE493370DE35B5E0
- generatedChecksum: 2B5072810107E051495C4B6379DEDA4E
  logicalPath: config\pic32mz_w1_curiosity\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 2B5072810107E051495C4B6379DEDA4E
- generatedChecksum: 59892AF04F939DE38670ECB116630EAC
  logicalPath: config\pic32mz_w1_curiosity\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 59892AF04F939DE38670ECB116630EAC
- generatedChecksum: 407D8CE5F0C091BCEBB78967FECBE53E
  logicalPath: config\pic32mz_w1_curiosity\peripheral\i2c\master
  name: plib_i2c1_master.h
  physicalPath: peripheral\i2c\master
  security: NON_SECURE
  type: HEADER
  userChecksum: 407D8CE5F0C091BCEBB78967FECBE53E
- generatedChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
  logicalPath: config\pic32mz_w1_curiosity\peripheral\i2c\master
  name: plib_i2c_master_common.h
  physicalPath: peripheral\i2c\master
  security: NON_SECURE
  type: HEADER
  userChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\pic32mz_w1_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: 79557AEFF1105797385F9C4EE40A5C4F
  logicalPath: config\pic32mz_w1_curiosity
  name: p32MZ1025W104132.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 79557AEFF1105797385F9C4EE40A5C4F
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;../src/packs/PIC32MZ1025W104132_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;../src/packs/PIC32MZ1025W104132_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
