files:
- generatedChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
  logicalPath: config/pic32mz_w1_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
- generatedChecksum: F848CC26B49DC444830609F770E3978F
  logicalPath: config/pic32mz_w1_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: F848CC26B49DC444830609F770E3978F
- generatedChecksum: E5FDC4C12B921E94BF607210B083284A
  logicalPath: config/pic32mz_w1_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E5FDC4C12B921E94BF607210B083284A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 256365FFCA2EA9E5891D7AAA554D7704
  logicalPath: config/pic32mz_w1_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 256365FFCA2EA9E5891D7AAA554D7704
- generatedChecksum: 76C6E35D15B5D0AC116CED498343C1D6
  logicalPath: config/pic32mz_w1_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 76C6E35D15B5D0AC116CED498343C1D6
- generatedChecksum: FD9710DF2A13B3EF35332108D05E96BD
  logicalPath: config/pic32mz_w1_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: FD9710DF2A13B3EF35332108D05E96BD
- generatedChecksum: 6C68EFD897A9E81DFA6A594C937CE697
  logicalPath: config/pic32mz_w1_curiosity/peripheral/power
  name: plib_power.c
  physicalPath: peripheral/power
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6C68EFD897A9E81DFA6A594C937CE697
- generatedChecksum: 3395BC7859A61CF74BB26386EF635C14
  logicalPath: config/pic32mz_w1_curiosity/peripheral/rcon
  name: plib_rcon.c
  physicalPath: peripheral/rcon
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3395BC7859A61CF74BB26386EF635C14
- generatedChecksum: 45D06C2B633EF6E09EE25A3655FF78FA
  logicalPath: config/pic32mz_w1_curiosity/peripheral/tmr1
  name: plib_tmr1.c
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: SOURCE
  userChecksum: 45D06C2B633EF6E09EE25A3655FF78FA
- generatedChecksum: AE604F3000CBB648C9C8BB7EA99F10F2
  logicalPath: config/pic32mz_w1_curiosity/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: AE604F3000CBB648C9C8BB7EA99F10F2
- generatedChecksum: 290251D6FF0845DC4259E0EF74DCB657
  logicalPath: config/pic32mz_w1_curiosity
  name: pmu_init.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 290251D6FF0845DC4259E0EF74DCB657
- generatedChecksum: 42A948E504602741B0D592C55FCD9A7B
  logicalPath: config/pic32mz_w1_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 42A948E504602741B0D592C55FCD9A7B
- generatedChecksum: 249F96908B5E579B008BB43605FA1781
  logicalPath: config/pic32mz_w1_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 249F96908B5E579B008BB43605FA1781
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_w1_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_w1_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F4C7B8A950B1D12FF6EC959D0A996B5B
  logicalPath: config/pic32mz_w1_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: F4C7B8A950B1D12FF6EC959D0A996B5B
- generatedChecksum: 4A6B9DAAC2733B35710DC4A5C33A361D
  logicalPath: config/pic32mz_w1_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 4A6B9DAAC2733B35710DC4A5C33A361D
- generatedChecksum: 3F8566A81CB3A43B5592B426231D90A9
  logicalPath: config/pic32mz_w1_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 3F8566A81CB3A43B5592B426231D90A9
- generatedChecksum: 71E49D4F47F8764F635BAFE58809F3A3
  logicalPath: config/pic32mz_w1_curiosity/peripheral/power
  name: plib_power.h
  physicalPath: peripheral/power
  security: NON_SECURE
  type: HEADER
  userChecksum: 71E49D4F47F8764F635BAFE58809F3A3
- generatedChecksum: 2D9E373A39FB85C5243574B8D2F7EA52
  logicalPath: config/pic32mz_w1_curiosity/peripheral/rcon
  name: plib_rcon.h
  physicalPath: peripheral/rcon
  security: NON_SECURE
  type: HEADER
  userChecksum: 2D9E373A39FB85C5243574B8D2F7EA52
- generatedChecksum: 32D7539D9231F3C159ABECE91A0281EA
  logicalPath: config/pic32mz_w1_curiosity/peripheral/tmr1
  name: plib_tmr1.h
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 32D7539D9231F3C159ABECE91A0281EA
- generatedChecksum: 69E7C8CDAB1B32838331EE261170CEA4
  logicalPath: config/pic32mz_w1_curiosity/peripheral/tmr1
  name: plib_tmr1_common.h
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 69E7C8CDAB1B32838331EE261170CEA4
- generatedChecksum: 2B111FC8ADC9E50611E481BE82CD3982
  logicalPath: config/pic32mz_w1_curiosity/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 2B111FC8ADC9E50611E481BE82CD3982
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mz_w1_curiosity/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mz_w1_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: 5A572F472102C65199D46D0D6E3E66AD
  logicalPath: config/pic32mz_w1_curiosity
  name: p32MZ1025W104132.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 5A572F472102C65199D46D0D6E3E66AD
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
