configName: pic32mz_w1_curiosity
folderName: pic32mz_w1_curiosity
format_version: v1.0
frameworkPath: ..\..\..\..
processor: PIC32MZ1025W104132
projectName: low_power_modes_pic32mz_w1_curiosity
settings:
  PackageFilter: bsp;core;csp
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.3.177\atdf\PIC32MZ1025W104132.atdf
