files:
- generatedChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
  logicalPath: config/pic32mz_w1_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
- generatedChecksum: 2D9F9E2DB7A361CF0DE77C5D7BC30757
  logicalPath: config/pic32mz_w1_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2D9F9E2DB7A361CF0DE77C5D7BC30757
- generatedChecksum: 015D4E98CA1DE6C118C421A0B6022440
  logicalPath: config/pic32mz_w1_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 015D4E98CA1DE6C118C421A0B6022440
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: CB847F5E9E80464F0595B2323A1D17BB
  logicalPath: config/pic32mz_w1_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: CB847F5E9E80464F0595B2323A1D17BB
- generatedChecksum: A90CF70DE8A653471CEEEEC0EA940320
  logicalPath: config/pic32mz_w1_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: A90CF70DE8A653471CEEEEC0EA940320
- generatedChecksum: A2BEAF440AC19A571FE122C9629DD9F0
  logicalPath: config/pic32mz_w1_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A2BEAF440AC19A571FE122C9629DD9F0
- generatedChecksum: 9EA79A532D72DCD1FAA8CC2714746396
  logicalPath: config/pic32mz_w1_curiosity/peripheral/i2c/slave
  name: plib_i2c1_slave.c
  physicalPath: peripheral/i2c/slave
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9EA79A532D72DCD1FAA8CC2714746396
- generatedChecksum: 290251D6FF0845DC4259E0EF74DCB657
  logicalPath: config/pic32mz_w1_curiosity
  name: pmu_init.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 290251D6FF0845DC4259E0EF74DCB657
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mz_w1_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 46BDFC0FBE43125CC8A7AC93B89D72B8
  logicalPath: config/pic32mz_w1_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 46BDFC0FBE43125CC8A7AC93B89D72B8
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_w1_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_w1_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F4C7B8A950B1D12FF6EC959D0A996B5B
  logicalPath: config/pic32mz_w1_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: F4C7B8A950B1D12FF6EC959D0A996B5B
- generatedChecksum: 2B5072810107E051495C4B6379DEDA4E
  logicalPath: config/pic32mz_w1_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 2B5072810107E051495C4B6379DEDA4E
- generatedChecksum: FB30E8BC8C3C1257D0CBF426B67AF5BF
  logicalPath: config/pic32mz_w1_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: FB30E8BC8C3C1257D0CBF426B67AF5BF
- generatedChecksum: DED28185122FE19E0755EFE96AE03279
  logicalPath: config/pic32mz_w1_curiosity/peripheral/i2c/slave
  name: plib_i2c1_slave.h
  physicalPath: peripheral/i2c/slave
  security: NON_SECURE
  type: HEADER
  userChecksum: DED28185122FE19E0755EFE96AE03279
- generatedChecksum: C9C7B78D76F4B3314A05BB48A51AF31D
  logicalPath: config/pic32mz_w1_curiosity/peripheral/i2c/slave
  name: plib_i2c_slave_common.h
  physicalPath: peripheral/i2c/slave
  security: NON_SECURE
  type: HEADER
  userChecksum: C9C7B78D76F4B3314A05BB48A51AF31D
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config/pic32mz_w1_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: 38B8D278EA69C81FF16A6EEA4989D1D1
  logicalPath: config/pic32mz_w1_curiosity
  name: p32MZ1025W104132.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 38B8D278EA69C81FF16A6EEA4989D1D1
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
