configName: pic32mz_w1_curiosity
folderName: ''
format_version: v1.0
frameworkPath: ../../../../..
processor: PIC32MZ1025W104132
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;crypto;cryptoauthlib;csp;gfx;micrium_ucos3;net;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.3.168\atdf\PIC32MZ1025W104132.atdf
