files:
- generatedChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
  logicalPath: config/pic32mz_w1_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AB67D8A7D0606ADFF3E9184E6CB5B5F9
- generatedChecksum: 20FF00545B6A2F38F3C7417F2DA8A8AC
  logicalPath: config/pic32mz_w1_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 20FF00545B6A2F38F3C7417F2DA8A8AC
- generatedChecksum: E01576FC5DCCED36A806FD17EE2D28C3
  logicalPath: config/pic32mz_w1_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E01576FC5DCCED36A806FD17EE2D28C3
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: DB2CFDF7306BB38193C16A084F982FF8
  logicalPath: config/pic32mz_w1_curiosity/peripheral/adchs
  name: plib_adchs.c
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: SOURCE
  userChecksum: DB2CFDF7306BB38193C16A084F982FF8
- generatedChecksum: A377BA84F92E117318E6913FA4119A8B
  logicalPath: config/pic32mz_w1_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: A377BA84F92E117318E6913FA4119A8B
- generatedChecksum: B95EEA87E94A5AC8F7FCFA464EB95E42
  logicalPath: config/pic32mz_w1_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: B95EEA87E94A5AC8F7FCFA464EB95E42
- generatedChecksum: B9A7E80E230C680E4D73D765BEAE8D7C
  logicalPath: config/pic32mz_w1_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: B9A7E80E230C680E4D73D765BEAE8D7C
- generatedChecksum: D8AB74DFC0A2CF06DF38F81E8848BE3C
  logicalPath: config/pic32mz_w1_curiosity/peripheral/tmr1
  name: plib_tmr1.c
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: SOURCE
  userChecksum: D8AB74DFC0A2CF06DF38F81E8848BE3C
- generatedChecksum: AE604F3000CBB648C9C8BB7EA99F10F2
  logicalPath: config/pic32mz_w1_curiosity/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: AE604F3000CBB648C9C8BB7EA99F10F2
- generatedChecksum: 290251D6FF0845DC4259E0EF74DCB657
  logicalPath: config/pic32mz_w1_curiosity
  name: pmu_init.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 290251D6FF0845DC4259E0EF74DCB657
- generatedChecksum: 42A948E504602741B0D592C55FCD9A7B
  logicalPath: config/pic32mz_w1_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 42A948E504602741B0D592C55FCD9A7B
- generatedChecksum: 891F07C42376E07E1A28EFC86073B83D
  logicalPath: config/pic32mz_w1_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 891F07C42376E07E1A28EFC86073B83D
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_w1_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_w1_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: C3972F912E996C00F701E5E0153C01B5
  logicalPath: config/pic32mz_w1_curiosity/peripheral/adchs
  name: plib_adchs.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: C3972F912E996C00F701E5E0153C01B5
- generatedChecksum: D005FAC6B0E4B73A93EC384550B9DD4B
  logicalPath: config/pic32mz_w1_curiosity/peripheral/adchs
  name: plib_adchs_common.h
  physicalPath: peripheral/adchs
  security: NON_SECURE
  type: HEADER
  userChecksum: D005FAC6B0E4B73A93EC384550B9DD4B
- generatedChecksum: F4C7B8A950B1D12FF6EC959D0A996B5B
  logicalPath: config/pic32mz_w1_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: F4C7B8A950B1D12FF6EC959D0A996B5B
- generatedChecksum: 2B5072810107E051495C4B6379DEDA4E
  logicalPath: config/pic32mz_w1_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 2B5072810107E051495C4B6379DEDA4E
- generatedChecksum: D9B00CCF87095896FD2DE8B5A025A4CA
  logicalPath: config/pic32mz_w1_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: D9B00CCF87095896FD2DE8B5A025A4CA
- generatedChecksum: 32D7539D9231F3C159ABECE91A0281EA
  logicalPath: config/pic32mz_w1_curiosity/peripheral/tmr1
  name: plib_tmr1.h
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 32D7539D9231F3C159ABECE91A0281EA
- generatedChecksum: 69E7C8CDAB1B32838331EE261170CEA4
  logicalPath: config/pic32mz_w1_curiosity/peripheral/tmr1
  name: plib_tmr1_common.h
  physicalPath: peripheral/tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 69E7C8CDAB1B32838331EE261170CEA4
- generatedChecksum: 2B111FC8ADC9E50611E481BE82CD3982
  logicalPath: config/pic32mz_w1_curiosity/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 2B111FC8ADC9E50611E481BE82CD3982
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mz_w1_curiosity/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mz_w1_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: 5A572F472102C65199D46D0D6E3E66AD
  logicalPath: config/pic32mz_w1_curiosity
  name: p32MZ1025W104132.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 5A572F472102C65199D46D0D6E3E66AD
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
