files:
- generatedChecksum: 39FF52903D784BEF79D3640DC1072AFA
  logicalPath: config\pic32mz_w1_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 39FF52903D784BEF79D3640DC1072AFA
- generatedChecksum: CA1E6A54112BCE3EE4235E13E8F81669
  logicalPath: config\pic32mz_w1_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA1E6A54112BCE3EE4235E13E8F81669
- generatedChecksum: 623F64F5EE8C4811FBD8BA948342C6B8
  logicalPath: config\pic32mz_w1_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 623F64F5EE8C4811FBD8BA948342C6B8
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 5A6CFF6AED6D44BCF41D78827F69FC3E
  logicalPath: config\pic32mz_w1_curiosity\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5A6CFF6AED6D44BCF41D78827F69FC3E
- generatedChecksum: D76BE921761B4B30B30E87D0C9F11F3F
  logicalPath: config\pic32mz_w1_curiosity\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: D76BE921761B4B30B30E87D0C9F11F3F
- generatedChecksum: 90D14B6CCD1A38263C25E5ED078A5176
  logicalPath: config\pic32mz_w1_curiosity\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 90D14B6CCD1A38263C25E5ED078A5176
- generatedChecksum: 0E85B0AB5FCB309535FF33FDEA0982C4
  logicalPath: config\pic32mz_w1_curiosity\peripheral\icap
  name: plib_icap1.c
  physicalPath: peripheral\icap
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E85B0AB5FCB309535FF33FDEA0982C4
- generatedChecksum: 1A6F78907CA4300156425C1382FAFAA7
  logicalPath: config\pic32mz_w1_curiosity\peripheral\ocmp
  name: plib_ocmp3.c
  physicalPath: peripheral\ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1A6F78907CA4300156425C1382FAFAA7
- generatedChecksum: C1B0DE2D23016F7C2BFBFC5043AEB053
  logicalPath: config\pic32mz_w1_curiosity\peripheral\tmr
  name: plib_tmr2.c
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: C1B0DE2D23016F7C2BFBFC5043AEB053
- generatedChecksum: DB373754AA6BF7CBA01136B07F9AA4B0
  logicalPath: config\pic32mz_w1_curiosity\peripheral\uart
  name: plib_uart1.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: DB373754AA6BF7CBA01136B07F9AA4B0
- generatedChecksum: 9A49A2339A0774ACCBC2178A9EE76586
  logicalPath: config\pic32mz_w1_curiosity
  name: system_pmu_mldo_trim.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9A49A2339A0774ACCBC2178A9EE76586
- generatedChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
  logicalPath: config\pic32mz_w1_curiosity\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
- generatedChecksum: 900E0A30A8DE172DCEDB46BA722C6A81
  logicalPath: config\pic32mz_w1_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 900E0A30A8DE172DCEDB46BA722C6A81
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mz_w1_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mz_w1_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 9238A3759A2C6748FE493370DE35B5E0
  logicalPath: config\pic32mz_w1_curiosity\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 9238A3759A2C6748FE493370DE35B5E0
- generatedChecksum: 2B5072810107E051495C4B6379DEDA4E
  logicalPath: config\pic32mz_w1_curiosity\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 2B5072810107E051495C4B6379DEDA4E
- generatedChecksum: 3C52CEA231878411E3950ADD556AF20C
  logicalPath: config\pic32mz_w1_curiosity\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C52CEA231878411E3950ADD556AF20C
- generatedChecksum: C735FE07D839BEF0340E5DD22C2DCC74
  logicalPath: config\pic32mz_w1_curiosity\peripheral\icap
  name: plib_icap1.h
  physicalPath: peripheral\icap
  security: NON_SECURE
  type: HEADER
  userChecksum: C735FE07D839BEF0340E5DD22C2DCC74
- generatedChecksum: B75BC5AEF7A117FB761A3A8548E16E3D
  logicalPath: config\pic32mz_w1_curiosity\peripheral\icap
  name: plib_icap_common.h
  physicalPath: peripheral\icap
  security: NON_SECURE
  type: HEADER
  userChecksum: B75BC5AEF7A117FB761A3A8548E16E3D
- generatedChecksum: E30FFC13DBD9F668569DE45E56387DCD
  logicalPath: config\pic32mz_w1_curiosity\peripheral\ocmp
  name: plib_ocmp3.h
  physicalPath: peripheral\ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: E30FFC13DBD9F668569DE45E56387DCD
- generatedChecksum: C7376B9C0FE98B35880E7395A16846B2
  logicalPath: config\pic32mz_w1_curiosity\peripheral\ocmp
  name: plib_ocmp_common.h
  physicalPath: peripheral\ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: C7376B9C0FE98B35880E7395A16846B2
- generatedChecksum: 612994C7F3C27F2CFA2621C1F65D4068
  logicalPath: config\pic32mz_w1_curiosity\peripheral\tmr
  name: plib_tmr2.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 612994C7F3C27F2CFA2621C1F65D4068
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config\pic32mz_w1_curiosity\peripheral\tmr
  name: plib_tmr_common.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: F196D990F65FF1D2130D5ADAEEC8FFAB
  logicalPath: config\pic32mz_w1_curiosity\peripheral\uart
  name: plib_uart1.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: F196D990F65FF1D2130D5ADAEEC8FFAB
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config\pic32mz_w1_curiosity\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config\pic32mz_w1_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: 79557AEFF1105797385F9C4EE40A5C4F
  logicalPath: config\pic32mz_w1_curiosity
  name: p32MZ1025W104132.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 79557AEFF1105797385F9C4EE40A5C4F
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;../src/packs/PIC32MZ1025W104132_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_w1_curiosity;../src/packs/PIC32MZ1025W104132_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
