format_version: v1.0
type: UniqueComponent
attributes: {id: rng}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: RNGCON_PLEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '64'}
  - type: KeyValueSet
    attributes: {id: RNGCON_TRNGMODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Hex
    attributes: {id: RNGCON_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: rng, value: '2112'}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: rng}
